### ISSUE TITLE
Create a reviewer memo

### ISSUE THREAD

**Issue by fsolt** [fsolt/meritocracy#10]
include paragraphs for each issue
[Memo.txt](https://github.com/fsolt/meritocracy/files/273082/Memo.txt)
File should be a .Rnw but has .txt extension to make GitHub happy

here's the PDF too: [Memo.pdf](https://github.com/fsolt/meritocracy/files/273088/Memo.pdf)

Verify by Hu

**Comment by sammo3182** [comment]
Sorry, Erico @dongericoyu. My schedule left no time to wait for you to create the memo template. So, I created a very rough one by myself in 4141c4d. Please free to work on it or create a better one. If you do the latter, I will appreciate it very much if you could copy my responses to your memo.

**Comment by dongericoyu** [comment]
I have a suggestion for Hu: your response to the reviewers' comments is very detailed, but also too long for a single point/issue (as I compare it with Fred's model response memo).
I will continue revising the memo in the incoming few days.

**Comment by dongericoyu** [comment]
I have two concerns with regards to the issues in the memo:
(1) In the first issue of "re-frame the tone of the paper", I may write the response in a overly humble way.

(2) We haven't address this comment: Reviewer 1 concerned that the inequality data of commuter zones (CZs) is measured in an earlier period than the time of the survey, and questioned whether inequality changed dramatically overtime.
