### ISSUE TITLE
DV (Reviewer #2) 

### ISSUE THREAD

**Issue by sammo3182** [fsolt/meritocracy#11]
Replicate analysis in NJL's footnote 5.
We use 2005 and 2006 Pewdata to conduct analysis with model 1 to show it is still different from NJL's result (probably in the appendix for Footnote 5). The result should be put in the appendix.

Verify by Hu

**Comment by sammo3182** [comment]
I reviewed the Appendix A. Everything is fine, except that we are supposed to conduct a "restrict" reproduction in the appendix, however, why none of our models includes union member and unemployment? Forgive me if we discussed this issue, although I didn't recall. If we haven't addressed it, do we need to explain why not having these two variables in the model? @dongericoyu @fsolt 
In c763d52493e25e5719ced5e14ff05559cdbafb64, I only updated the page number in the memo and give a very brief discussion about Reviewer 1's concern in item 4.

**Comment by dongericoyu** [comment]
I'm just back and am able to read all your updates (thanks for the free internet). I will look into the Appendix tonight.

**Comment by fsolt** [comment]
No data in the survey.  In fact, there was no unemployment data in the surveys NJL used either, but you shouldn't get me started...

On Jun 20, 2016, at 4:44 PM, Yue Hu <notifications@github.com<mailto:notifications@github.com>> wrote:

I reviewed the Appendix A. Everything is fine, except that we are supposed to conduct a "restrict" reproduction in the appendix, however, why none of our models includes union member and unemployment? Forgive me if we discussed this issue, although I didn't recall. If we haven't addressed it, do we need to explain why not having these two variables in the model? @dongericoyuhttps://github.com/dongericoyu @fsolthttps://github.com/fsolt
In c763d52https://github.com/fsolt/meritocracy/commit/c763d52493e25e5719ced5e14ff05559cdbafb64, I only updated the page number in the memo and give a very brief discussion about Reviewer 1's concern in item 4.

##

**Comment by sammo3182** [comment]
My bad :p
