### ISSUE TITLE
IV: get the county level data

### ISSUE THREAD

**Issue by sammo3182** [fsolt/meritocracy#12]
1. get the gini data at county level from the ACS
2. get the county level data for other variables.(verify whether there is data for our controls at the same level).

Verify by Erico.

**Comment by jsong10** [comment]
http://factfinder.census.gov/faces/nav/jsf/pages/download_center.xhtml#none

We can download the county-level data from the above link (choose "2009 ACS 5-year estimates" for dataset, and choose "All Counties within United States" for county). I think NJL obtained the Gini coefficient from this data. There is no Gini variable in this dataset, so I think we need to calculate it manually.

**Comment by dongericoyu** [comment]
Ok. I download the data and take a look at them. According to a documentation on gini index by the Census Bureau, there is a variable of average annual household income of each county(see the csv file I upload, HC01_EST_VC45 is the annual household income). What we need is just to calculate the gini index by this data. I will ask Fred whether he has a package or command in R to automatically calculate it.
[ACS_09_5YR_S0601.txt](https://github.com/fsolt/meritocracy/files/274267/ACS_09_5YR_S0601.txt)

Jungming, would you mind to check the data and variable for me and see whether it is the correct variable we should use?

**Comment by jsong10** [comment]
I will check it!

**Comment by fsolt** [comment]
The _average_ annual household income is insufficient to calculate the gini, which measures the distribution _across_ households.  If there truly isn't a Census-generated gini (and I'm not completely convinced there isn't: the "American FactFinder" offers quite limited access to Census data; as I mentioned in our meeting, DataFerret is the Census's data retrieval tool), then we'll need the variables containing the number of households in each income category within each county to calculate a gini.

The Census Bureau's code for the gini is B19083, btw.

**Comment by fsolt** [comment]
Okay, I've confirmed that B19083 exists in the ACS 2005-2009 5yr and that it's not available through the American FactFinder; see https://www.census.gov/content/dam/Census/programs-surveys/acs/tech-doc/summary-file/TablesinSFonly.xls .  This link indicates that it is accessible via FTP, i.e., with the DataFerret.  It also indicates that the data are available in the Summary File, which is here: http://www2.census.gov/programs-surveys/acs/summary_file/2009/data/ .  "Summary File" is perhaps misleading, though: Census Bureau Summary Files include nearly everything.

**Comment by jsong10** [comment]
http://dataferrett.census.gov/
Go to the above link with Internet Explorer (and update the latest Java), and launch DataFerrett. 

http://dataferrett.census.gov/acs/ACS_5yrsf_UserGuide.pdf
Follow the steps in the userguide, which can be downloaded by the above link. 
Select Summarized data, 2005-2009, 5-year summary file, and B19083, and also select geographics (county level).

If you followed the above steps, you will get the email from DataFerrett, which includes the link for the data. 

http://tabulation.api.census.gov/TheDataWeb_Tabulation/servlet/TabulationServlet/jungmin_songiolfrspgscr.html

This link contains the link for the GINI Index data of all counties. (You can open it by Excel)
Codebook can be downloaded in Step2 of DataFerrett ("Save Selected Variables Codebook" -- located in the right side of the screen).

**Comment by fsolt** [comment]
Don't forget that we also need all the controls . . .

On May 24, 2016, at 8:57 AM, Jungmin Song <notifications@github.com<mailto:notifications@github.com>> wrote:

http://dataferrett.census.gov/
Go to the above link with Internet Explorer (and update the latest Java), and launch DataFerrett.

http://dataferrett.census.gov/acs/ACS_5yrsf_UserGuide.pdf
Follow the steps in the userguide, which can be downloaded by the above link.
Select Summarized data, 2005-2009, 5-year summary file, and B19083, and also select geographic.

If you followed the above steps, you will get the email from DataFerrett, which includes the link for the data.

http://tabulation.api.census.gov/TheDataWeb_Tabulation/servlet/TabulationServlet/jungmin_songiolfrspgscr.html

This link contains the link for the GINI Index data of all counties. (You can open it by Excel)
Codebook can be downloaded in Step2 of DataFerrett ("Save Selected Variables Codebook" -- located in the right side of the screen).

##

**Comment by jsong10** [comment]
http://tabulation.api.census.gov/TheDataWeb_Tabulation/servlet/TabulationServlet/jungmin_songionbophiscr.html

@dongericoyu 
Erico, through the above link, you can download the asc file that contains GINI Index (B19083) Median Household Income (B19013), Total Population (B01003), and Black Population (B02001_003E). Percent Black will be calculated by "B02001_003E/B01003 \* 100". Codebook is attached.

[codebook.txt](https://github.com/fsolt/meritocracy/files/282936/codebook.txt)

For Bush Vote 2004 variable (the percent of voters in each county voting for Bush in the 2004 election), NJL said that it was obtained from David Leip's "Atlas of U.S. Presidential Elections" at http://uselectionatlast.org. However, it looks like it requires me to pay for accessing the county-level data ($57). I've searched other sources for this variable, but most of them did not give me the access. Do you have any idea about this, Fred? @fsolt

**Comment by fsolt** [comment]
I've replicated it with public sources elsewhere in our work--you'll find it in the Rnw files.   I'm tempted to go ahead and buy it, too, though.

On May 25, 2016, at 4:55 PM, Jungmin Song <notifications@github.com<mailto:notifications@github.com>> wrote:

http://tabulation.api.census.gov/TheDataWeb_Tabulation/servlet/TabulationServlet/jungmin_songionbophiscr.html

@dongericoyuhttps://github.com/dongericoyu
Erico, through the above link, you can download the asc file that contains GINI Index (B19083) Median Household Income (B19013), Total Population (B01003), and Black Population (B02001_003E). Percent Black will be calculated by "B02001_003E/B01003 \* 100". Codebook is attached.

codebook.txthttps://github.com/fsolt/meritocracy/files/282936/codebook.txt

For Bush Vote 2004 variable (the percent of voters in each county voting for Bush in the 2004 election), NJL said that it was obtained from David Leip's "Atlas of U.S. Presidential Elections" at http://uselectionatlast.org. However, it looks like it requires me to pay for accessing the county-level data ($57). I've searched other sources for this variable, but most of them did not give me the access. Do you have any idea about this, Fred? @fsolthttps://github.com/fsolt

##

**Comment by jsong10** [comment]
[2004 Bush.xlsx](https://github.com/fsolt/meritocracy/files/285280/2004.Bush.xlsx)
[ACS Data.xlsx](https://github.com/fsolt/meritocracy/files/285281/ACS.Data.xlsx)

http://bactra.org/election/vote-counts-with-NE-aggregated

I got the Bush 2004 data from the above link, and converted them into an excel file. I will try to merge these two data by county codes. @dongericoyu

**Comment by fsolt** [comment]
I repeat: I have already done this work.  Check out the Rnw.  If you need help finding the right chunk, ask at the meeting tomorrow.  Do not waste time doing work that's already been done.

On May 26, 2016, at 3:29 PM, Jungmin Song <notifications@github.com<mailto:notifications@github.com>> wrote:

2004 Bush.xlsxhttps://github.com/fsolt/meritocracy/files/285280/2004.Bush.xlsx
ACS Data.xlsxhttps://github.com/fsolt/meritocracy/files/285281/ACS.Data.xlsx

http://bactra.org/election/vote-counts-with-NE-aggregated

I got the Bush 2004 data from the above link, and converted them into an excel file. I will try to merge these two data by county codes. @dongericoyuhttps://github.com/dongericoyu

##
