### ISSUE TITLE
IV: justification of CZ

### ISSUE THREAD

**Issue by sammo3182** [fsolt/meritocracy#14]
Justify using CZs with Chetty's work. This part should be in the content.

**Comment by kwhudson** [comment]
Ready for verification. Looks like no one got assigned to double check/revise this one. @sammo3182 @dongericoyu @jsong10

**Comment by sammo3182** [comment]
I reviewed the modification in ffd04cb for issue #14 and the response in the memo. The argument is pretty clear. Dorn does elaborate more about the advantages of CZs than Chetty. Good job! No further needs to modify. But Kevin @kwhudson, I changed your citation on Dorn's dissertation to his paper published in American Economic Review. To me, citing an academic paper sounds more specific and reliable than citing a whole dissertation.

**Comment by fsolt** [comment]
The diss cite came out of Chetty et al. (I saw it there too, Kevin), so good job tracking down Dorn's article, Hu.
