### ISSUE TITLE
Potential issues I found

### ISSUE THREAD

**Issue by sammo3182** [fsolt/meritocracy#2]
299 could go into the plot note.
457 \citep
469 "to over" are in Italic, try \$ instead.

Figure A.2 Why not just "Model 1" rather than "Model 1A"?

**Comment by fsolt** [comment]
299 agreed (it's there already; I'll delete it here)
457 good catch!
469 ha! caught that myself yesterday

To distinguish these models from the ones in the text.  But seeing your question makes me think we should go with "A1" instead of "1A" to match with the figure labels.
