### ISSUE TITLE
Kevan proofreading

### ISSUE THREAD

**Issue by kwhudson** [fsolt/meritocracy#4]
Line 72 :  "Meritocracy---that idea that if one works hard" 
-should it be "the idea" rather than "that idea"?

Line 76 - I agree with Erico, I think it should be "advance", not "advanced"

Line 106:  "We restrict our focus here, though, to the article's main analysis on the rejection of meritocracy"
-Should it be "analysis of"?

Otherwise I don't see much - sorry for the delay in getting this to you.

**Comment by fsolt** [comment]
Line 72: Yes.

Line 76: Actually, "advances", because we're talking about a (singular) paper, not the three authors, but I'm with you both on the present tense.

Line 106: I was trying to avoid repeating 'of' in "analysis of the rejection of meritocracy", but yes.
