### ISSUE TITLE
Tone: Revise "snarky" tone

### ISSUE THREAD

**Issue by fsolt** [fsolt/meritocracy#7]
Huber and Stephens quote--deal with it in the conclusion
delete "strangely", "oddly", etc. in favor of description
Strangely: "Although NJL says this variable ranges from 0 to 1, it actually ranges from .21 to 1, so it never takes on zero value"

**Comment by fsolt** [comment]
Kevan first, then Fred

**Comment by kwhudson** [comment]
I've reworded the response. I think it's much more in line with what we discussed Monday.
