### ISSUE TITLE
IV: Better justify interaction critique

### ISSUE THREAD

**Issue by fsolt** [fsolt/meritocracy#9]
Add cite to Berry, Golder, and Milton (2012) to the effect that marginal effect plots are necessary and are the way things are done now

Additional discussion in the memo of the methodological literature on interactions:

"Reviewer 2's comments indicate that we did not provide an adequate explanation of methodolists' guidance to political scientists on the use and interpretation of interaction terms."

**Comment by fsolt** [comment]
Hu first, then Erico

**Comment by sammo3182** [comment]
Modifications are done in the paper and the responses were added to the memo. See 4141c4d.
Please check them, Erico @dongericoyu, at your earliest convenience.

**Comment by sammo3182** [comment]
I reviewed the original version but found very limited stuffs to delete. Erico @dongericoyu,  I need your help to modify or simplify my response. Please remove anything you think unnecessary or redundant. I'll appreciate it.

In ed64367, there are only some language modifications in the memo. Moreover, I created the bibliography file and fix the citation presenting.

**Comment by dongericoyu** [comment]
Copy that Hu. I will review it again after I finish my part.
